- hosts: api_servers

  vars:
    repo_url: https://github.com/charsyam/simple_scrap
    app_name: hello_flask
    webapps_dir: /home/charsyam/simple_scrap
    target_dir: simple2
    repo_remote: origin
    repo_version: master

  tasks:
    - name: deploy code
      action: git repo={{ repo_url }} dest={{ webapps_dir }}/{{ app_name }} remote={{ repo_remote }} version={{ repo_version }}
      notify:
        - restart gunicorn

    - name: install dependencies for projects
      sudo: yes
      action: pip requirements={{ webapps_dir }}/{{ app_name }}/{{ target_dir }}/requirements.txt state=present

    - name: copy gunicorn config
      sudo: yes
      template: src=files/gunicorn.j2 dest=/etc/init/gunicorn.conf
      notify:
        - restart gunicorn

  handlers:
    - name: restart gunicorn
      sudo: yes
      service: name=gunicorn state=restarted