- hosts: api_servers
  remote_user: ubuntu

  vars:
    repo_url: https://github.com/bowbowbow/node-scrapper
    app_name: node-scrapper
    webapps_dir: /home/ubuntu/
    repo_remote: origin
    repo_version: master

  tasks:
    - name: remove
      shell: rm -rf ./{{ app_name }}

    - name: deploy code
      action: git repo={{ repo_url }} dest={{ webapps_dir }}/{{ app_name }} remote={{ repo_remote }} version={{ repo_version }}

    - name: install dependencies for projects
      shell: npm install --prefix ./{{ app_name }}
      notify:
        - node start

  handlers:
    - name: node start
      shell: forever ./{{ app_name }}/app.js