- hosts: api_servers
  sudo: yes
  tasks:
    - name: Installs git
      apt: pkg=git-core state=installed update_cache=true
    - name: Installs python-dev
      apt: pkg=python-dev state=installed update_cache=true
    - name: Installs python-pip
      apt: pkg=python-pip state=installed update_cache=true