- hosts: api_servers
  remote_user: ubuntu
  sudo: yes
  tasks:
    - name: Installs git
      apt: pkg=git-core state=installed update_cache=true

    - name: pkg update for node
      sudo: yes
      shell: curl -sL https://deb.nodesource.com/setup_6.x | sudo -E bash -

    - name: Installs nodejs
      apt: pkg=nodejs state=installed update_cache=true

    - name: Installs build-essential
      apt: pkg=build-essential state=installed update_cache=true

    - name: Install forever module
      shell: npm install -g forever
