- hosts: api_servers
  remote_user: ubuntu
  sudo: yes
  tasks:
    - name: Installs redis-server
      apt: pkg=redis-server state=installed update_cache=true
      notify:
        - start redis

  handlers:
    - name: start redis
      service: name=redis-server state=started